version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: evote-pg-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321123321
      POSTGRES_DB: evote_kz
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: evote-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: evote-backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    ports:
      - "7000:7000"

volumes:
  pgdata:
