version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: evote-pg-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321123321
      POSTGRES_DB: evote_kz
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-create-dbs.sql:/docker-entrypoint-initdb.d/init-create-dbs.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: evote-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: evote-backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    ports:
      - "7000:7000"

  egov:
    build:
      context: ./services/egov
      dockerfile: Dockerfile
    container_name: evote-egov
    env_file:
      - ./services/egov/.env
    depends_on:
      - db
    ports:
      - "7002:7002"

  otp:
    build:
      context: ./services/otp
      dockerfile: Dockerfile
    container_name: evote-otp
    env_file:
      - ./services/otp/.env
    depends_on:
      - db
    ports:
      - "7001:7001"
volumes:
  pgdata:
