import "@/styles/globals.scss";

import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Providers } from "@/store/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Sidebar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
